#spring:
#  application:
#     name: ad-eureka
#
#server:
#   port: 8000
#
#eureka:
#   instance:
#      hostname: localhost
#   client:
#      fetch-registry: false
#      registry-with-eureka: false
#      service-url:
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      healthcheck:
#        enabled: false

spring:
  application:
     name: ad-eureka
  profiles: server1
server:
  port: 8000
eureka:
  instance:
    hostname: server1
    prefer-id-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka,http://server3:8002/eureka
feign:
  hystrix:
    enabled: true


spring:
  application:
     name: ad-eureka
  profiles: server2
server:
  port: 8001
eureka:
  instance:
    hostname: server2
    prefer-id-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka,http://server3:8002/eureka
feign:
  hystrix:
    enabled: true

spring:
  application:
     name: ad-eureka
  profiles: server3
server:
  port: 8002
eureka:
  instance:
    hostname: server3
    prefer-id-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka,http://server2:8001/eureka
feign:
  hystrix:
    enabled: true